#!/bin/bash

#if (( "$EUID" == 0 )); then
#        printf "not running with elevated privileges\n"
#        exit 0
#fi

base_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
src_dir="$base_dir/src"
build_dir="$base_dir/build"
binary_outpath="$base_dir/gpkih"
cmakelists="$base_dir/CMakeLists.txt"
log_stderr="$base_dir/.error.log"

# Commands to run in order to build the executable
# note: this will be executed inside build/ 
commands=("cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .." "make -j" "cp gpkih $binary_outpath")
verbose=true

if [ -e "$log_stderr" ]; then
        rm "$log_stderr"
fi

args=($@)
argc=$#

if ! [ -e "$build_dir" ]; then
        mkdir "$build_dir"
        if (( $? != 0 )); then
                $verbose && printf "couldn't create build dir '%s'\n" "$build_dir"
                exit 1
        fi
fi

cd "$build_dir"

for arg in "${args[@]}"; do
        if [ "$arg" == "-h" ]; then
                cat << EOF

Usage: setup [optional-subopts]

[optional-subopts]
  none haha

EOF
        exit 0
elif [[ "$arg" == "-q" || "$arg" == "--quiet" ]]; then
        verbose=false
elif [[ "$arg" == "-docker" || "$arg" == "--docker" ]]; then
        # Check that service is running
        if ! systemctl is-active docker --quiet; then
                # Try to manually start it
                if systemctl start docker --quiet; then
                        printf "[+] Docker service started"
                else
                        printf "[!] Couldn't start service docker, exiting..."
                        exit $?
                fi
        fi

        if ! docker ps &>/dev/null; then
                printf "[+] Don't have permissions to list dockers, exiting...\n"
                exit 1
        fi

        for os in debian ubuntu archlinux fedora alpine; do
                pids=()
                # -T : no TTY, required to avoid 'no input TTY available' problems
                # --rm : deletes the container when stopped, which will be after the command returns
                compile_command="docker-compose run -T --rm $os bash ./entry.sh compile /home/gpkih/docker/"$os"_results"
                
                printf "[+] OS: %s - %s\n" "$os" "$compile_command" 
                $compile_command &

                pids+=($!)
        done 
        

        printf "[+] Waiting for processes to finish...\n"
        waitpid ${pids[@]}

        exit 0
fi
        
done

for command in "${commands[@]}"; do
        $verbose && printf "[running] %s\n" "$command" 
        
        if $verbose; then
          $command 2>> "$log_stderr" 
        else
          $command &>/dev/null
        fi
        
        if (( $? != 0 )); then
                $verbose && printf "Something failed running '%s', check '%s' for more information\n" "$command" "$log_stderr"
                exit $?
        fi 
done

$verbose && printf "[info] gpkih succesfully compiled: %s\n" "$binary_outpath"
exit 0