#!/bin/bash

####### User args #######
read -a args -r <<< "$@"
argc=$#
#########################

################################# Variables #################################
baseDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
buildDir="$baseDir/build"
srcDir="$baseDir/src"
binaryOutpath="$baseDir/gpkih"
cmakelists="$baseDir/CMakeLists.txt"
logStderr="$baseDir/.error.log"
logStdout="$baseDir/.out.log"
quiet=false
dockerOsList=(debian ubuntu archlinux fedora alpine)

declare -A pmList
pmList["apt"]="install"
pmList["pacman"]="-S"
pmList["dnf"]="install"
pmList["apk"]="add"
pmList["zypper"]="install"
pmList["guix"]="install"

pm="" # package manager to use if a package is required to be installed
pmInstallOpt="" # package manager subopt to install e.g 'install' on apt

##### Optionally compilable features #####
GPKIH_ENABLE_DEBUGGING=false

#-DCMAKE_EXPORT_COMPILE_COMMANDS=1 -> create a build/compile_commands.json that comes in handy for certain scenarios
commands=("cmake .." "make -j" "cp $buildDir/gpkih $binaryOutpath") # [!] note : this will be executed inside build/ 
#############################################################################

function gecho(){
        $quiet || echo -en "$@"
}

function __setPackageManager(){
        for i in "${!pmList[@]}"; do
                if command -v "$i" &>/dev/null; then
                        pm="$i"
                        pmInstallOpt="${pmList[$i]}"
                        break
                fi
        done
        
        if [ -z "$pm" ]; then
                $quiet && exit 1
                gecho "Couldn't set package manager, not in the following list?:"
                for i in "${!pmList[@]}"; do
                        gecho "$i" 
                done
                gecho "\nnote: you can add it manually to the pmList variable inside the script\n" && exit 0
        fi
}

function __generateDocumentation(){
        local doxyfile="$baseDir/src/Doxyfile"

        if (( $EUID == 0 )); then
                gecho "Won't generate documentation as root\n" && exit 1
        fi

        [ ! -e "$doxyfile" ] && { gecho "Doxyfile not found: '%s'\n" "$doxyfile"; exit 1; }
        
        # Check for doxygen
        if ! command -v doxygen &>/dev/null; then
                $quiet && exit 1
                read -rp "Doxygen not installed, install? y/n: " ans
                if [[ "${ans,,}" != "y" && "${ans,,}" != "yes" ]]; then
                        exit 1
                fi
                __setPackageManager
                sudo $pm $pmInstallOpt doxygen || { gecho "Couldn't install doxygen\n"; exit 1; }
                (( $? != 0 )) && exit 1
        fi

        cd "$srcDir" && doxygen "$doxyfile" 1>/dev/null 2>"$logStderr"

        (( $? != 0 )) && { gecho "Failed running doxygen command: 'doxygen $doxyFile'\nError logs can be found at '$logStderr'\n"; exit 0; }

        gecho "Doxygen documentation succesfully created, can be found at '$baseDir/documentation'\n"
        exit 0
}

function __runDockerTests(){
        local dockerDir="$baseDir/docker"
        local dockerResultsFile="$dockerDir/results"
        local compileCmd

        # Check that binary is available
        if ! command -v docker &>/dev/null; then
                read -rp "[!] Docker not installed, install? y/n: " ans
                if [[ "${ans,,}" != "y" && "${ans,,}" != "yes" ]]; then
                        exit 0
                fi
                __setPackageManager
                sudo $pm $pmInstallOpt docker || { gecho "[!] Couldn't install docker aborting...\n"; exit 1; }
        fi

        # Check that service is running
        if ! systemctl is-active docker --quiet; then
                # Try to manually start it
                if systemctl start docker --quiet; then
                        gecho "[+] Docker service started\n"
                else
                        gecho "[!] Couldn't start service docker, exiting...\n"
                        exit $?
                fi
        fi

        if ! docker ps &>/dev/null; then
                gecho "[+] Don't have permissions to list dockers, maybe run with sudo? exiting...\n"
                exit 1
        fi

        # Empty any previous `results` contents and create if not existing
        > "$dockerResultsFile" &>/dev/null  ||  { gecho "[!] Can't write to results file '$dockerResultsFile', aborting...\n"; exit 0; }

        # Set permissions to allow others (docker _gpkih user) writing to it
        chmod 766 "$dockerResultsFile"
        
        cd "$dockerDir" || { gecho "[!] Couldn't cd to docker directory '$dockerDir'\n"; exit 1; }
        for os in "${dockerOsList[@]}"; do
                # -T : no TTY, required to avoid 'no input TTY available' problems
                # --rm : deletes the container when stopped, which will be after the command returns
                compileCmd="docker-compose run --quiet-pull -T --rm $os bash ./compile.sh /home/gpkih/docker/results"
                gecho "[+] Operating System: $os\n"
                $quiet && $compileCmd &>/dev/null || $compileCmd
                # waitpid $!
                $quiet || cat << EOF 
[+] Compilation results: $(grep -E "^Compilation" "$dockerResultsFile" | tail -1 | awk '{print $3}')

EOF
        done 

        gecho "[+] Specific checks' results can be found @ '$dockerResultsFile'\n"
        exit 0
}

function usage(){
        cat << EOF
Name: gpkih setup script
Description: helps compiling the tool, generating documentation and testing in other OSes

Usage: ./setup <options>

* Options *
  -h      | --help              = display this message and exit
  -q      | --quiet             = don't print anything to console 0:success else failure
  -docker | --docker            = used for developing, will create ${#dockerOsList[@]} containers to test compiling and running gpkih: ${dockerOsList[@]}
  -docs   | --documentation     = create doxygen documentation - *not super fancy*
  -d      | --define <KEY=VAL>  = add preprocessing directives
  -ed     | --enable-debugging  = enable debugging capabilities - default false
EOF
        exit 0
}

function parse(){
        for (( i=0 ; i < $argc ; ++i )); do
                arg="${args[$i],,}"
                if [[ "$arg" == "-q" || "$arg" == "--quiet" ]]; then
                        quiet=true
                        args=("${args[@]:0:$i}" "${args[@]:$i}")
                        break
                fi 
        done

        for (( i=0 ; i < $argc ; ++i )); do
                arg="${args[$i],,}"
                if [[ "$arg" == "-h" || "$arg" == "--help" || "$arg" == "help" || "$arg" == "h" || "$arg" == "--h" || "$arg" == "-help" ]]; then
                        usage
                elif [[ "$arg" == "-docker" || "$arg" == "--docker" ]]; then
                        __runDockerTests
                elif [[ "$arg" == "-docs" || "$arg" == "--documentation" ]]; then
                        __generateDocumentation
                elif [[ "$arg" == "-d" || "$arg" == "--define" ]]; then
                        if ! grep -q '=' <<< "${args[++i]}"; then 
                                gecho "[!] Wrong syntax '${args[++i]}', right syntax KEY=VAL\nnote the missing '='\n"
                                exit 1
                        fi
                        commands[0]="${commands[0]} -D${args[++i]}"
                elif [[ "$arg" == "-ed" || "$arg" == "--enable-debugging" ]]; then
                        GPKIH_ENABLE_DEBUGGING=true
                else
                        printf "[!] Unkown option '%s'\n" "$arg"
                fi
        done

        if $GPKIH_ENABLE_DEBUGGING; then
                gecho "[+] Debugging capabilities ENABLED\n" && commands[0]="${commands[0]} -DGPRINTING_ENABLE_DEBUGGING=1"
        else
                gecho "[+] Debugging capabilities DISABLED\n" && commands[0]="${commands[0]} -DGPRINTING_ENABLE_DEBUGGING=0"
        fi
}

function main(){
        
        > "$logStderr" &>/dev/null  || { gecho "[!] Don't have permissions to write stdout log file '$logStderr'\n"; exit 1; }
        > "$logStdout" &>/dev/null  || { gecho "[!] Don't have permissions to write stderr log file '$logStdout'\n"; exit 1; }

        parse

        if ! [ -e "$buildDir" ]; then
                mkdir "$buildDir"
                if (( $? != 0 )); then
                        gecho "[!] Couldn't create build dir '$buildDir'\n"¡
                        exit 1
                fi
        fi
        
        cd "$buildDir"

        for command in "${commands[@]}"; do
                
                gecho "[running] $command\n"
                $command 1>> "$logStdout" 2>> "$logStderr" 
                
                (( $? != 0 )) && gecho "Something failed running '$command'\ncheck '$logStderr' for more information\n" && exit $?
        done
        
        gecho "[info] gpkih succesfully compiled: $binaryOutpath\n[info] building process' logs can be found at '$logStdout'\n"
        
        exit 0        
}

main